<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <AssemblyName>StoreDebt.Desktop</AssemblyName>
    <RootNamespace>StoreDebt.Desktop</RootNamespace>
    <Version>0.3.0</Version>
    <Authors>Radwan Abd alhady Ahmed</Authors>
    <Product>دفتر ديون المحل</Product>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Data.Sqlite" Version="10.0.12" />
    <PackageReference Include="System.Speech" Version="10.0.0" />
  </ItemGroup>

</Project>
